@echo off
REM ================================================================
REM   AI Property Market - TEST RUNNER (Windows, one click)
REM
REM   THIS FILE IS DELIBERATELY PURE ASCII. READ THIS FIRST.
REM
REM   Two Windows facts forced that decision, both measured
REM   on this machine on 30.09.2026:
REM
REM   1) The console here runs code page 866 (OEM Cyrillic)
REM      while Python reports stdout.encoding = cp1251 (ANSI
REM      Cyrillic). They are NOT the same. Cyrillic written as
REM      cp1251 into a CP 866 console is mojibake.
REM
REM   2) cmd.exe reads a .bat file byte by byte and remembers
REM      its position. If the code page changes WHILE the batch
REM      is running, the remaining bytes get re-interpreted and
REM      the script falls apart into garbage lines such as
REM          'is not recognized as an internal command'
REM      That happened with "chcp 65001" and a batch file that
REM      contained Cyrillic echo lines.
REM
REM   So: no Cyrillic in this file, and chcp is safe.
REM   The REPORT ITSELF is fully Bulgarian - it is generated by
REM   tests\report_generator.py, which is a normal UTF-8 file
REM   and is not parsed by cmd.exe.
REM
REM   Nothing here writes to storage/ or storage_raw/.
REM ================================================================
setlocal EnableExtensions
cd /d "%~dp0\.."

title AI Property Market - Tests

set "PY="
set "REPORT_DIR=tests\_last_run"
set "JUNIT=%REPORT_DIR%\junit.xml"
set "TARGET=tests"

REM ------------------------------------------------------------
REM  UTF-8 console. Safe now: this file is pure ASCII, so
REM  cmd.exe cannot mis-parse the remainder when the code page
REM  changes. The original page is restored on the way out so
REM  a console this was launched from is left as it was.
REM ------------------------------------------------------------
set "OLD_CP="
for /f "tokens=2 delims=:" %%a in ('chcp 2^>nul') do set "OLD_CP=%%a"
set "OLD_CP=%OLD_CP: =%"
chcp 65001 >nul 2>&1

REM ------------------------------------------------------------
REM  ARGUMENTS
REM
REM  --no-wait  finish immediately instead of waiting for a
REM              keypress. Needed by automation and by any
REM              script that cannot press a key.
REM  anything else is passed straight to pytest.
REM ------------------------------------------------------------
set "WAIT_FOR_KEY=1"
set "PYTEST_ARGS=%TARGET%"
set "SHOW_HELP="

:parse_args
if "%~1"=="" goto args_done
if /i "%~1"=="--no-wait" (
    set "WAIT_FOR_KEY=0"
    shift
    goto parse_args
)
if /i "%~1"=="/?" (
    set "SHOW_HELP=1"
    shift
    goto parse_args
)
if /i "%~1"=="--help" (
    set "SHOW_HELP=1"
    shift
    goto parse_args
)
if "%PYTEST_ARGS%"=="%TARGET%" (
    set "PYTEST_ARGS=%1"
) else (
    set "PYTEST_ARGS=%PYTEST_ARGS% %1"
)
shift
goto parse_args

:args_done
if not "%SHOW_HELP%"=="1" goto :run_tests

:print_usage
echo.
echo  Usage: run_tests.bat [--no-wait] [pytest args...]
echo.
echo    --no-wait    finish immediately, do not wait for a key
echo    --help       show this text
echo    anything else is passed straight to pytest
echo.
echo  Examples:
echo    run_tests.bat
echo    run_tests.bat tests\test_matcher.py
echo    run_tests.bat -k area
echo    run_tests.bat --no-wait -q
echo.
goto :done

:run_tests

REM ------------------------------------------------------------
REM  PYTHON
REM  .venv wins: the tests are written against its versions.
REM  If it is missing we say so instead of silently using PATH.
REM ------------------------------------------------------------
if exist ".venv\Scripts\python.exe" (
    set "PY=.venv\Scripts\python.exe"
) else (
    set "PY=python"
    echo.
    echo [WARN] .venv\Scripts\python.exe not found.
    echo [WARN] Falling back to "python" from PATH. Versions may
    echo [WARN] differ from the ones the tests expect.
    echo.
)

"%PY%" -c "import pytest" >nul 2>&1
if errorlevel 1 goto :cannot_run

if not exist "%REPORT_DIR%" mkdir "%REPORT_DIR%" >nul 2>&1

echo ================================================================
echo    AI Property Market  -  test suite
echo ================================================================
echo.
echo [INFO] Target      : %PYTEST_ARGS%
echo [INFO] Report file : %JUNIT%
echo.
echo ------------------------------------------------------------
echo  Running...
echo ------------------------------------------------------------
echo.

REM ------------------------------------------------------------
REM  PYTEST
REM
REM  --junitxml  gives report_generator.py exact numbers
REM  --tb=short  a full traceback is noise with 600+ tests
REM  -rf         summary of failures right away
REM  --durations slowest tests, free from pytest
REM
REM  Output is NOT redirected - you must see it on screen.
REM ------------------------------------------------------------
"%PY%" -m pytest %PYTEST_ARGS% ^
    --tb=short ^
    -rf ^
    --junitxml="%JUNIT%" ^
    --durations=10

set "RC=%ERRORLEVEL%"

echo.
echo ------------------------------------------------------------
echo  Building report...
echo ------------------------------------------------------------
echo.

REM  The report is generated once, printed to the console and
REM  saved as UTF-8 text. Redirecting stdout to a file would
REM  mix encodings; report_generator handles both destinations.
"%PY%" "tests\report_generator.py" "%JUNIT%" %RC% --save "%REPORT_DIR%\report.txt"
set "RCRC=%ERRORLEVEL%"

if not "%RCRC%"=="0" (
    echo.
    echo [WARN] Report generator exited with code %RCRC%^.
    echo [WARN] The pytest output above is still valid.
    echo.
)

echo.
echo [INFO] Full report (text) : %REPORT_DIR%\report.txt
echo [INFO] Full report (xml)  : %JUNIT%
echo.

:done
if "%WAIT_FOR_KEY%"=="0" goto :skip_wait

echo ================================================================
echo.
echo    The window stays open.
echo    Press any key to close it.
echo.
echo ================================================================
echo.

:wait_and_exit
REM  ReadKey via PowerShell works both on a double click and
REM  from a console. If it is unavailable we fall back to
REM  pause, so one keypress always closes the window - and the
REM  window never closes on its own.
set "WAITRC=0"
powershell -NoProfile -ExecutionPolicy Bypass -Command "try { $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown') } catch { exit 1 }" >nul 2>&1
if errorlevel 1 set "WAITRC=1"

if "%WAITRC%"=="1" (
    echo.
    pause
)

:skip_wait
if defined OLD_CP chcp %OLD_CP% >nul 2>&1

if not defined RC set "RC=0"

echo.
echo [EXIT] Test run finished with code %RC%^.
echo.

if "%RC%"=="0" (
    endlocal
    exit /b 0
)

endlocal
exit /b %RC%


REM ================================================================
REM  PYTEST IS NOT AVAILABLE
REM ================================================================
:cannot_run
if defined OLD_CP chcp %OLD_CP% >nul 2>&1
echo.
echo ================================================================
echo    CANNOT RUN TESTS
echo ================================================================
echo.
echo    pytest is not available for:
echo      %PY%
echo.
echo    Fix it with:
echo      .venv\Scripts\python.exe -m pip install -r requirements.txt
echo.
echo    Nothing was executed, so no report was produced.
echo.
echo    The window stays open so you can read this.
echo.
pause
endlocal
exit /b 2
